import { ArrowRight, Building2, Globe2, Home, Search } from "lucide-react";
import { useState } from "react";

export function EnterpriseHome() {
  return <EnterpriseHomeContent />;
}

function EnterpriseHomeContent() {
  const [intent, setIntent] = useState("Buy");
  const [city, setCity] = useState("");

  return <div className="bg-white text-[#192c45]">
    <main>
      <section className="relative min-h-[610px] overflow-hidden bg-slate-950"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=85&w=2200" alt="Modern architectural home" className="absolute inset-0 h-full w-full object-cover opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-950/50 to-slate-950/20" /><div className="relative mx-auto flex min-h-[610px] max-w-[1480px] items-center px-5 py-20 lg:px-10"><div className="max-w-2xl text-white"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-300">India's property intelligence network</p><h1 className="mt-5 text-5xl font-extrabold leading-[0.98] tracking-tight sm:text-7xl">Find your dream home.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Search millions of properties, understand the market, and move from curiosity to keys with one trusted workspace.</p><div className="mt-10 max-w-3xl rounded-2xl bg-white p-2 text-slate-900 shadow-2xl"><div className="flex gap-1 border-b border-slate-100 px-2">{["Buy", "Rent", "Sell"].map((item) => <button key={item} onClick={() => setIntent(item)} className={`border-b-2 px-4 py-3 text-sm font-bold ${intent === item ? "border-[#d9232e] text-[#d9232e]" : "border-transparent text-slate-500"}`}>{item}</button>)}</div><div className="grid gap-2 p-2 sm:grid-cols-[1fr_auto]"><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3"><Search className="h-5 w-5 text-[#d9232e]" /><input value={city} onChange={(event) => setCity(event.target.value)} placeholder={intent === "Sell" ? "Enter your property address" : "Search city, locality or project"} className="w-full bg-transparent text-sm outline-none" /></label><a href={intent === "Sell" ? "/sell" : "/app"} className="flex items-center justify-center gap-2 rounded-xl bg-[#d9232e] px-7 py-3 text-sm font-bold text-white hover:bg-[#b91d27]">{intent === "Sell" ? "Get valuation" : "Search"}<ArrowRight className="h-4 w-4" /></a></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-white/70"><span>Popular:</span><button onClick={() => setCity("Bangalore")} className="hover:text-white">Bangalore</button><button onClick={() => setCity("Mumbai")} className="hover:text-white">Mumbai</button><button onClick={() => setCity("Delhi NCR")} className="hover:text-white">Delhi NCR</button><button onClick={() => setCity("Hyderabad")} className="hover:text-white">Hyderabad</button></div></div></div></section>
      <section className="mx-auto max-w-[1200px] px-5 py-16 lg:px-10"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#d9232e]">Everything property</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight">A smarter way to move.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[[Home, "Property appraisals", "Get an intelligent view of value, demand, and neighborhood potential."], [Building2, "Free registration", "Create your workspace and keep every property decision in one place."], [Globe2, "Large coverage", "Explore cities, localities, projects, and international property signals."]].map(([Icon, title, copy]) => <article key={title as string} className="group border border-slate-200 bg-white p-8 text-center shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="mx-auto flex h-20 w-20 items-center justify-center border-2 border-emerald-400 bg-slate-950 text-emerald-300"><Icon className="h-9 w-9" /></div><h3 className="mt-7 text-xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy as string}</p></article>)}</div></section>
      <section className="bg-[#101e31] px-5 py-16 text-white lg:px-10"><div className="mx-auto grid max-w-[1200px] items-center gap-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-300">For owners, agents & builders</p><h2 className="mt-4 text-4xl font-extrabold tracking-tight">Put your property in front of the right people.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">Post a property, understand the response, manage enquiries, and turn market intelligence into your next action.</p><a href="/sell" className="mt-8 inline-flex items-center gap-2 rounded-full bg-emerald-400 px-6 py-3 font-bold text-slate-950">Explore selling tools <ArrowRight className="h-4 w-4" /></a></div><div className="rounded-3xl bg-black p-7 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Seller workspace</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/50">Listing views</p><p className="mt-2 text-3xl font-bold">2,480</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/50">AI valuation</p><p className="mt-2 text-3xl font-bold">₹1.35Cr</p></div></div><div className="mt-5 rounded-xl bg-emerald-400 p-4 text-sm font-bold text-slate-950">Your next best action: refresh your hero image.</div></div></div></section>
    </main>
  </div>;
}
