"use client";

import { ArrowRight, Building2, ChevronDown, Globe2, Heart, Home, Menu, Search, UserRound, X } from "lucide-react";
import { useState } from "react";

const navItems = [
  { label: "Buy", groups: [["Popular choices", "Ready to move", "Owner properties", "Budget homes", "New projects"], ["Property types", "Flats", "Villas", "Plots", "Office spaces"], ["Budget", "Under ₹50 Lac", "₹50 Lac - ₹1 Cr", "₹1 Cr - ₹1.5 Cr", "Above ₹1.5 Cr"], ["Explore", "Localities", "Projects", "Find an agent", "Property guides"]] },
  { label: "Rent", groups: [["Popular choices", "Flats for rent", "Owner properties", "No brokerage", "PG / co-living"], ["Property types", "Apartments", "Independent houses", "Villas", "Commercial spaces"], ["Rent tools", "Rent agreement", "Tenant services", "Rental trends", "Moving checklist"]] },
  { label: "Sell", groups: [["For owner", "Post property", "My dashboard", "Sell / rent packages"], ["For agent & builder", "My dashboard", "Sales enquiry", "Developer lounge", "Ad packages"], ["Selling tools", "Property valuation", "Find an agent", "Rates & trends", "PropWorth"]] },
  { label: "Home Loans", groups: [["Apply now", "Home loans", "Balance transfer", "Loan against property"], ["Explore", "EMI calculator", "Loan eligibility", "Credit score", "Prepayment"], ["Partners", "SBI home loan", "HDFC home loan", "Axis home loan", "LIC housing finance"]] },
  { label: "Insights", groups: [["Market intelligence", "Rates & trends", "Buy vs rent", "Locality guides", "Investment outlook"], ["Advice", "First-time buyer", "Home loan guides", "Interior ideas", "Legal explainers"]] },
];

export function EnterpriseHome() {
  const [activeNav, setActiveNav] = useState<string | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [intent, setIntent] = useState("Buy");
  const [city, setCity] = useState("");

  return <div className="min-h-screen bg-white text-[#192c45]">
    <div className="h-1 bg-[#d9232e]" />
    <header className="sticky top-0 z-50 border-b border-slate-200 bg-white shadow-sm"><div className="mx-auto flex h-[72px] max-w-[1480px] items-center gap-6 px-5 lg:px-10"><a href="/" className="flex shrink-0 items-center gap-2"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#d9232e] text-white"><Building2 className="h-5 w-5" /></span><span className="text-xl font-extrabold tracking-tight">EstateIQ</span></a><nav className="hidden flex-1 items-stretch gap-1 lg:flex">{navItems.map((item) => <button key={item.label} onClick={() => setActiveNav(activeNav === item.label ? null : item.label)} className={`flex items-center gap-1 border-b-2 px-4 text-sm font-semibold ${activeNav === item.label ? "border-[#d9232e] text-[#d9232e]" : "border-transparent text-slate-600 hover:text-[#d9232e]"}`}>{item.label}<ChevronDown className="h-4 w-4" /></button>)}</nav><div className="ml-auto flex items-center gap-2"><a href="/login" className="hidden items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50 sm:flex"><UserRound className="h-4 w-4" />Login</a><a href="/sell" className="hidden rounded-full bg-[#d9232e] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#b91d27] sm:block">Post Property <span className="ml-1 rounded-full bg-amber-400 px-2 py-0.5 text-[10px] text-slate-900">FREE</span></a><button onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 lg:hidden" aria-label="Open menu">{mobileOpen ? <X /> : <Menu />}</button></div></div>{activeNav && <div className="absolute left-0 right-0 top-full hidden border-b border-slate-200 bg-white shadow-xl lg:block"><div className="mx-auto grid max-w-[1320px] gap-8 px-10 py-7" style={{ gridTemplateColumns: `repeat(${Math.min(navItems.find((item) => item.label === activeNav)?.groups.length ?? 3, 4)}, minmax(0, 1fr))` }}>{navItems.find((item) => item.label === activeNav)?.groups.map(([heading, ...links]) => <div key={heading}><h3 className="border-b border-slate-200 pb-3 text-base font-semibold">{heading}</h3><div className="mt-3 space-y-3">{links.map((link) => <a key={link} href="#" className="block text-sm text-slate-600 hover:text-[#d9232e]">{link}</a>)}</div></div>)}</div></div>}{mobileOpen && <div className="border-t border-slate-200 bg-white p-5 lg:hidden"><div className="space-y-2">{navItems.map((item) => <a key={item.label} href={item.label === "Buy" ? "/app" : `/${item.label.toLowerCase().replace(" ", "-")}`} className="block rounded-lg px-3 py-3 font-semibold hover:bg-slate-50">{item.label}</a>)}<a href="/login" className="block rounded-lg bg-[#d9232e] px-3 py-3 font-bold text-white">Login / Sign up</a></div></div>}</header>
    <main>
      <section className="relative min-h-[610px] overflow-hidden bg-slate-950"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=85&w=2200" alt="Modern architectural home" className="absolute inset-0 h-full w-full object-cover opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-950/50 to-slate-950/20" /><div className="relative mx-auto flex min-h-[610px] max-w-[1480px] items-center px-5 py-20 lg:px-10"><div className="max-w-2xl text-white"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-300">India's property intelligence network</p><h1 className="mt-5 text-5xl font-extrabold leading-[0.98] tracking-tight sm:text-7xl">Find your dream home.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Search millions of properties, understand the market, and move from curiosity to keys with one trusted workspace.</p><div className="mt-10 max-w-3xl rounded-2xl bg-white p-2 text-slate-900 shadow-2xl"><div className="flex gap-1 border-b border-slate-100 px-2">{["Buy", "Rent", "Sell"].map((item) => <button key={item} onClick={() => setIntent(item)} className={`border-b-2 px-4 py-3 text-sm font-bold ${intent === item ? "border-[#d9232e] text-[#d9232e]" : "border-transparent text-slate-500"}`}>{item}</button>)}</div><div className="grid gap-2 p-2 sm:grid-cols-[1fr_auto]"><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3"><Search className="h-5 w-5 text-[#d9232e]" /><input value={city} onChange={(event) => setCity(event.target.value)} placeholder={intent === "Sell" ? "Enter your property address" : "Search city, locality or project"} className="w-full bg-transparent text-sm outline-none" /></label><a href={intent === "Sell" ? "/sell" : "/app"} className="flex items-center justify-center gap-2 rounded-xl bg-[#d9232e] px-7 py-3 text-sm font-bold text-white hover:bg-[#b91d27]">{intent === "Sell" ? "Get valuation" : "Search"}<ArrowRight className="h-4 w-4" /></a></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-white/70"><span>Popular:</span><button onClick={() => setCity("Bangalore")} className="hover:text-white">Bangalore</button><button onClick={() => setCity("Mumbai")} className="hover:text-white">Mumbai</button><button onClick={() => setCity("Delhi NCR")} className="hover:text-white">Delhi NCR</button><button onClick={() => setCity("Hyderabad")} className="hover:text-white">Hyderabad</button></div></div></div></section>
      <section className="mx-auto max-w-[1200px] px-5 py-16 lg:px-10"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#d9232e]">Everything property</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight">A smarter way to move.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[[Home, "Property appraisals", "Get an intelligent view of value, demand, and neighborhood potential."], [Building2, "Free registration", "Create your workspace and keep every property decision in one place."], [Globe2, "Large coverage", "Explore cities, localities, projects, and international property signals."]].map(([Icon, title, copy]) => <article key={title as string} className="group border border-slate-200 bg-white p-8 text-center shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="mx-auto flex h-20 w-20 items-center justify-center border-2 border-emerald-400 bg-slate-950 text-emerald-300"><Icon className="h-9 w-9" /></div><h3 className="mt-7 text-xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy as string}</p></article>)}</div></section>
      <section className="bg-[#101e31] px-5 py-16 text-white lg:px-10"><div className="mx-auto grid max-w-[1200px] items-center gap-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-300">For owners, agents & builders</p><h2 className="mt-4 text-4xl font-extrabold tracking-tight">Put your property in front of the right people.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">Post a property, understand the response, manage enquiries, and turn market intelligence into your next action.</p><a href="/sell" className="mt-8 inline-flex items-center gap-2 rounded-full bg-emerald-400 px-6 py-3 font-bold text-slate-950">Explore selling tools <ArrowRight className="h-4 w-4" /></a></div><div className="rounded-3xl bg-black p-7 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Seller workspace</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/50">Listing views</p><p className="mt-2 text-3xl font-bold">2,480</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/50">AI valuation</p><p className="mt-2 text-3xl font-bold">₹1.35Cr</p></div></div><div className="mt-5 rounded-xl bg-emerald-400 p-4 text-sm font-bold text-slate-950">Your next best action: refresh your hero image.</div></div></div></section>
    </main>
    <footer className="bg-[#f4f4f2] px-5 pt-14 text-slate-700 lg:px-10"><div className="mx-auto grid max-w-[1200px] gap-10 pb-12 md:grid-cols-[1.1fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-2 font-extrabold text-slate-950"><Building2 className="h-5 w-5 text-[#d9232e]" />EstateIQ</div><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">A trusted property ecosystem for discovery, ownership, renting, and better decisions.</p><div className="mt-6 flex gap-2"><span className="rounded-full bg-slate-950 px-3 py-2 text-xs text-white">Google Play</span><span className="rounded-full bg-slate-950 px-3 py-2 text-xs text-white">App Store</span></div></div>{[["Properties in India", "Property in Mumbai", "Property in Bangalore", "Property in Delhi NCR", "New projects"], ["Property services", "Home loans", "Home interiors", "Property valuation", "Find an agent"], ["Company", "About EstateIQ", "Contact", "Terms & conditions", "Privacy policy"]].map(([heading, ...links]) => <div key={heading}><h3 className="font-bold text-slate-950">{heading}</h3><div className="mt-4 space-y-3 text-sm">{links.map((link) => <a key={link} href="#" className="block hover:text-[#d9232e]">{link}</a>)}</div></div>)}</div><div className="border-t border-slate-300 py-5"><div className="mx-auto flex max-w-[1200px] flex-wrap items-center justify-between gap-3 text-xs text-slate-500"><span>© 2026 EstateIQ. All rights reserved.</span><span className="flex items-center gap-2"><Heart className="h-3.5 w-3.5 text-[#d9232e]" /> Built for better property decisions</span></div></div></footer>
  </div>;
}
